In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

obs = np.array([
    [50, 70],
    [80,100],
    [60, 90],
    [30, 50],
    [20, 50]
])

row_names = ["Very Satisfied", "Satisfied", "Neutral", "Unsatisfied", "Very Unsatisfied"]
col_names = ["Smart Thermostat", "Smart Light"]
obs_df = pd.DataFrame(obs, index=row_names, columns=col_names)
obs_df


,Smart Thermostat,Smart Light
Very Satisfied,50,70
Satisfied,80,100
Neutral,60,90
Unsatisfied,30,50
Very Unsatisfied,20,50


In [ ]:
row_totals = obs.sum(axis=1)      
col_totals = obs.sum(axis=0)       
grand_total = obs.sum()           

expected = np.outer(row_totals, col_totals) / grand_total

expected_df = pd.DataFrame(expected, index=row_names, columns=col_names)

row_totals, col_totals, grand_total, expected_df


(array([120, 180, 150,  80,  70]),
 array([240, 360]),
 np.int64(600),
                   Smart Thermostat  Smart Light
 Very Satisfied                48.0         72.0
 Satisfied                     72.0        108.0
 Neutral                       60.0         90.0
 Unsatisfied                   32.0         48.0
 Very Unsatisfied              28.0         42.0)

In [ ]:
chi_square_components = (obs - expected)**2 / expected
chi_square_stat = chi_square_components.sum()

chi_square_components_df = pd.DataFrame(chi_square_components, index=row_names, columns=col_names)
chi_square_stat, chi_square_components_df



(np.float64(5.638227513227513),
                   Smart Thermostat  Smart Light
 Very Satisfied            0.083333     0.055556
 Satisfied                 0.888889     0.592593
 Neutral                   0.000000     0.000000
 Unsatisfied               0.125000     0.083333
 Very Unsatisfied          2.285714     1.523810)

In [ ]:
chi2, p_value, dof, expected_scipy = stats.chi2_contingency(obs, correction=False)

chi2, p_value, dof, expected_scipy


(np.float64(5.638227513227513),
 np.float64(0.22784371130697179),
 4,
 array([[ 48.,  72.],
        [ 72., 108.],
        [ 60.,  90.],
        [ 32.,  48.],
        [ 28.,  42.]]))

In [ ]:
alpha = 0.05
df = dof
critical_value = stats.chi2.ppf(1 - alpha, df)

print("Chi-square statistic:", chi2)
print("Degrees of freedom:", df)
print("Critical value at alpha=0.05:", critical_value)
print("p-value:", p_value)

if chi2 > critical_value:
    print("Decision: Reject H0 (there is an association).")
else:
    print("Decision: Fail to reject H0 (no significant association).")


Chi-square statistic: 5.638227513227513
Degrees of freedom: 4
Critical value at alpha=0.05: 9.487729036781154
p-value: 0.22784371130697179
Decision: Fail to reject H0 (no significant association).


In [ ]:

expected.min()   


n = grand_total   
min_dim = min(obs.shape) - 1
cramers_v = np.sqrt(chi2 / (n * min_dim))


cramers_v


np.float64(0.09693836111354054)

 ##### Hypothesis Testing


In [ ]:
import numpy as np
from math import sqrt
from scipy import stats

x_bar = 3050.0        
X_mean = 600.0        
sigma_X = 25.0         
n = 25                

mu_W = 1000 + 5 * X_mean    
sigma_W = 5 * sigma_X        

x_bar, mu_W, sigma_W, n


(3050.0, 4000.0, 125.0, 25)

In [ ]:
se = sigma_W / sqrt(n)              
z_stat = (x_bar - mu_W) / se        

se, z_stat


(25.0, -38.0)

In [ ]:
alpha = 0.05
z_critical = stats.norm.ppf(1 - alpha)   

p_value = 1 - stats.norm.cdf(z_stat)

z_critical, p_value


(np.float64(1.6448536269514722), np.float64(1.0))

In [ ]:
print("Sample mean (x̄):", x_bar)
print("Theoretical mean (μ0):", mu_W)
print("Population sd (σ):", sigma_W)
print("SE:", se)
print("Z statistic:", z_stat)
print("Z critical (alpha=0.05, one-tailed right):", z_critical)
print("p-value (right-tailed):", p_value)

if z_stat > z_critical:
    print("Decision: Reject H0 → evidence that mean > 4000 (costs higher).")
else:
    print("Decision: Fail to reject H0 → no evidence that mean > 4000.")


Sample mean (x̄): 3050.0
Theoretical mean (μ0): 4000.0
Population sd (σ): 125.0
SE: 25.0
Z statistic: -38.0
Z critical (alpha=0.05, one-tailed right): 1.6448536269514722
p-value (right-tailed): 1.0
Decision: Fail to reject H0 → no evidence that mean > 4000.
